# version: '3.8'
# services:
#   mongo:
#     image: mongo:6
#     restart: always
#     volumes:
#       - mongo-data:/data/db
#     ports:
#       - '27017:27017'
#   api:
#     build: .
#     ports:
#       - '4000:4000'
#     env_file: .env.example
#     depends_on:
#       - mongo
# volumes:
#   mongo-data:
